# Generated by Django 2.0.6 on 2018-06-24 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('portal', '0001_initial'), ('portal', '0002_workflow_status')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('category', models.CharField(choices=[('GLOBUS_GENOMICS', 'Globus Genomics'), ('JUPYTERHUB', 'Jupyterhub')], max_length=128)),
                ('data_store', models.TextField(blank=True)),
                ('description', models.CharField(blank=True, max_length=128)),
                ('input', models.ManyToManyField(blank=True, related_name='minid_input', to='search.Minid')),
                ('output', models.ManyToManyField(blank=True, related_name='minid_output', to='search.Minid')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('status', models.CharField(choices=[('READY', 'Ready'), ('RUNNING', 'Running'), ('COMPLETE', 'Complete')], default='READY', max_length=64)),
            ],
        ),
    ]
