# Generated by Django 2.0.6 on 2018-06-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='minid_email',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='profile',
            name='globus_genomics_apikey',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
