# Generated by Django 2.0.6 on 2018-08-14 20:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20180629_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workflow',
            name='metadata_store',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('GLOBUS_GENOMICS', 'Globus Genomics'), ('JUPYTERHUB', 'Jupyterhub'), ('WES', 'Workflow Execution Service')], max_length=128),
        ),
    ]
