# Generated by Django 2.0.6 on 2018-08-21 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_workflow_date_and_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('JUPYTERHUB', 'Jupyterhub'), ('WES', 'WES')], max_length=128),
        ),
    ]
