# Generated by Django 2.0.6 on 2018-08-21 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_rename_wes_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('JUPYTERHUB', 'Jupyterhub'), ('WES', 'WES'), ('TEST_COMPUTE', 'Test Compute'), ('TEST_TRANSFER', 'Test Transfer')], max_length=128),
        ),
    ]
